version: '3.5'

services:
  app:
    image: go-vending-app
    container_name: go-vending-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
      - ./templates/:/root/templates/
    env_file:
      - .env

  postgres:
    image: postgres:15.1-alpine
    container_name: go-postgres
    environment:
      - POSTGRES_USER=vending
      - POSTGRES_PASSWORD=vending
      - POSTGRES_DB=vending
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:5432"